# docker/dagster/Dockerfile_dagster
# Lightweight image for webserver and daemon (no application code)
FROM python:3.11-slim

WORKDIR /opt/dagster

# Install only Dagster packages
RUN pip install --no-cache-dir \
    dagster \
    dagster-webserver \
    dagster-postgres

# Set $DAGSTER_HOME and copy dagster.yaml and workspace.yaml here
ENV DAGSTER_HOME=/opt/dagster/dagster_home

RUN mkdir $DAGSTER_HOME

COPY dagster.yaml workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME

