FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONPATH=/opt/dagster/app/src

WORKDIR /opt/dagster/app

RUN pip install --no-cache-dir --upgrade pip
 
# Install dagster and any other dependencies the project requires
RUN \
    pip install \
        dagster \
        dagster-postgres \
        dagster-k8s \
        dagster-ssh \
        # other dependencies
        pandas

COPY . .

# Dagster user code gRPC port
EXPOSE 3030